### ISSUE TITLE
Deviation in the BBC functionality between (at least) LearnLib 0.14.0 and 0.16.0

### ISSUE THREAD

**Issue by MasWag** [LearnLib/automatalib#46]
Due to the update of `AbstractLTSminMonitorMealy` in 75b1987782c8f0167534a5e0b60ec285a11ab6f9, the behavior of the BBC functionality in LearnLib changed (at least) between 0.14.0 and 0.16.0. (Sorry, I have not tried 0.15.0) I believe that the previous behavior is the expected one.

Here is a concrete example to reproduce this deviation + a summary of the reason for the deviation in my understanding: https://github.com/MasWag/deviation-LearnLib-0.14.0-vs-0.16.0

**Comment by mtf90** [comment]
Dear @MasWag,

thanks for reporting this issue and providing a testcase for reproducing it. You are right, this has been a regression in one of our refactorings to better handle null values. Unfortunately, the current implementation is not really in line with the interface definitions (see [here](https://github.com/LearnLib/automatalib/blob/develop/core/src/main/java/net/automatalib/modelchecking/lasso/MealyLassoImpl.java#L54) as well) and we need to clean this up some time in the future.

I have added some test-cases in LearnLib (including the use-case you have described in your repo) so that we hopefully won't break things again.

I am currently a little bit busy with some side-projects. Can you live with using the 0.14 version or the current development version for now?

**Comment by MasWag** [comment]
Thanks a lot for your quick response. Yes, I will keep using LearnLib 0.14 for the time being.
