### ISSUE TITLE
IndexOutOfBoundsException in IncrementalMealyDAGBuilder when input word is longer than output word

### ISSUE THREAD

**Issue by BlobbyBob** [LearnLib/automatalib#77]
**Describe the bug**
When using automatalib, an IndexOutOfBoundsException occured when on inserting a pair in IncrementalMealyDAGBuilder.

**To Reproduce**
```java
import net.automatalib.alphabet.Alphabet;
import net.automatalib.alphabet.ArrayAlphabet;
import net.automatalib.incremental.mealy.dag.IncrementalMealyDAGBuilder;
import net.automatalib.word.Word;

public class Debug {
    public static void main(String[] args) {
        Alphabet<Symbol> alphabet = new ArrayAlphabet<>(Symbol.A);
        IncrementalMealyDAGBuilder<Symbol, Symbol> dagBuilder = new IncrementalMealyDAGBuilder<>(alphabet);
        dagBuilder.insert(Word.fromSymbols(Symbol.A, Symbol.A), Word.fromSymbols(Symbol.A));
    }

    public enum Symbol {
        A
    }
}
```

**Expected behavior**
Inserting to work as expected without crashing.

**Stack Trace**
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: 0
	at net.automatalib.word.EmptyWord.getSymbol(EmptyWord.java:60)
	at net.automatalib.incremental.mealy.dag.IncrementalMealyDAGBuilder.createSuffix(IncrementalMealyDAGBuilder.java:377)
	at net.automatalib.incremental.mealy.dag.IncrementalMealyDAGBuilder.insert(IncrementalMealyDAGBuilder.java:209)
	at Debug.main(Debug.java:13)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Java version: 11
 - AutomataLib version: 0.11.0

**Additional context**
Originally, I was using automatalib through learnlib (with the issue occuring in SULCache), so I'm not totally sure to which project this issue belongs. However, I didn't find any documentation that this behavior is wanted over here.

**Comment by mtf90** [comment]
Dear @BlobbyBob, the issue is that Mealy machines typically map inputs of length `n` to outputs of length `n` and the implementation assumes that this invariant holds. Now, inserting a trace `A A` that should map to `A` trips the implementation and the exception occcurs. This can probably be reported by a more meaningful error message, but it is primarily a usage error in my eyes.

**Comment by BlobbyBob** [comment]
Thanks for your response. So it is probably best to open the issue in the learnlib repo instead?

Nonetheless, a more meaningful error message or an assertion that both word length match would be very helpful instead of throwing a "generic" exception.

**Comment by mtf90** [comment]
Hm, you wrote that the issue occurred when using a `SULCache`. Typically, the `SUL` interface also suggests one-for-one semantics, so I wonder how you managed to construct traces with unequal length in the first place.

**Comment by BlobbyBob** [comment]
That is indeed an interesting question. I assumed the `SULCache` was at fault as the issue did not occur when I commented it out. I have made some other changes to the setup in the meantime, but I will try to find a minimal working example again.

**Comment by BlobbyBob** [comment]
As this might take some time, I will close the issue until then

**Comment by mtf90** [comment]
Sure, feel free to open it again if it turns out to be an actual issue with the cache. You may also enable assertions (`-ea`) to activate additional checks that may help you tracking down the issue.

If you are unsure about certain concepts in AutomataLib/LearnLib, don't hesitate to open a [discussion thread](https://github.com/LearnLib/learnlib/discussions) either.
